apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    app: init-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    env:
      - name: MY_ENV_VAR
        value: "This is an environment variable"
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c']
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']
    - name: init-mydb
      image: busybox
      command: ['sh', '-c']
      args: ['until nslookup mydb.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']