kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.29.2
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
- role: worker
  image: kindest/node:v1.29.2
- role: worker
  image: kindest/node:v1.29.2

# use this command for this kind version it works: kind create cluster --image kindest/node:v1.31.0 --name=default-cni --config=kind.yaml