apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-alll
  labels:
    env: configmap
spec:
  containers:
  - name: configmappod-all
    image: busybox:1.28
    envFrom:
      - configMapRef:
          name: config
    command: ['sh', '-c', 'echo Tha app is running! && sleep 3600']