apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
preemptionPolicy: PreemptLowerPriority # you do not need to set this field, as it is the default behavior
description: "This priority class should be used for high priority pods only."