apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-13T05:21:45Z"
  generation: 1
  labels:
    run: redis
    app: backend
    tier: springboot
  name: redis
  namespace: default
  resourceVersion: "66327"
  uid: 0e3ed8ea-c159-4933-b970-e82d615489b3
spec:
  containers:
  - image: redis
    imagePullPolicy: Always
    name: redis