apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mondodb-0
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongoddb-0"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mondodb-1
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongoddb-1"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mondodb-2
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongoddb-2"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mondodb-3
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongoddb-3"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mondodb-4
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongoddb-4"
  persistentVolumeReclaimPolicy: Retain