apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
    app: backend
    tier: springboot
  name: redis
  namespace: default
spec:
  containers:
  - image: redis
    imagePullPolicy: Always
    name: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}