apiVersion: v1
kind: Pod

metadata:
  name: nginx-storage

spec:
  containers:

  - image: nginx
    name: nginx

    volumeMounts:

    - name: data
      mountPath: /usr/share/nginx/html

  volumes:

  - name: data

    persistentVolumeClaim:
      claimName: demo-pvc

# Step 9: Watch the provisioning
# kubectl get pvc -w

# Expected:

# Pending

# ↓

# Bound

# Check the PV:

# kubectl get pv

# Example:

# pvc-fdc38ab8...

# 2Gi

# Bound
# Step 10: Verify in AWS

# Go to:

# EC2
#     ↓
# Elastic Block Store
#     ↓
# Volumes

# You should see:

# gp3
# 2 GiB
# In-use
# Attached

# The volume was created automatically.